# run `pre-commit autoupdate` to update tags (`rev`) to the latest versions
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10000"]
        stages: [commit]
      - id: check-ast
        stages: [commit]
      - id: check-docstring-first
        stages: [commit]
      - id: check-json
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: check-toml
        stages: [commit]
      - id: check-yaml
        # does not raise error for lines starting with !!
        args: ["--unsafe"]
        stages: [commit]
      - id: debug-statements
        stages: [commit]
      - id: detect-private-key
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: name-tests-test
        # test files start with test_ instead of ending with _test
        args: [-h]
        stages: [commit]
      - id: pretty-format-json
        args: ["--autofix"]
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        stages: [commit]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.265
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
        stages: [commit]
        exclude: ^pyproject\.toml$
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
        stages: [push]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        stages: [push]
  - repo: https://github.com/pdm-project/pdm
    rev: 2.5.3
    hooks:
      - id: pdm-lock-check
