site_name: readnext
site_description: A Hybrid Recommender System for Computer Science Papers
site_url: https://joel-beck.github.io/readnext/

repo_name: readnext
repo_url: https://github.com/joel-beck/readnext

theme:
  name: material
  icon:
    logo: material/meteor # built-in icon search at https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/?h=ic#search # noqa
  features:
    - content.code.copy # Adds a copy button to code blocks
    - content.tabs.link # Allows linking to specific tabs via URLs
    - navigation.expand # Expands the navigation menu for nested sections
    - navigation.instant # Enables instant navigation without page reloads
    - navigation.sections # Organizes the menu into sections based on headers
    - navigation.tracking # Tracks the user's progress through the documentation
    - search.highlight # Highlights search terms in the search results
    - search.suggest # Provides search suggestions while typing in the search bar
    - toc.follow # Automatically updates the table of contents as the user scrolls
  palette:
    - media: "(prefers-color-scheme: light)" # Light Mode
      scheme: default
      primary: "#193549"
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)" # Dark Mode
      scheme: slate
      primary: "#193549"
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"

plugins:
  - search # Enables search functionality

markdown_extensions:
  - admonition # Enables collapsible blocks with styled titles for notes, warnings, etc.
  - attr_list # Allows adding HTML attributes to elements using a consistent syntax
  - footnotes # Adds support for footnotes in Markdown
  - markdown.extensions.attr_list # Alternative syntax for adding HTML attributes to elements
  - md_in_html # Allows embedding Markdown inside HTML tags
  - pymdownx.details # Enables collapsible content sections using the details HTML tag
  - pymdownx.emoji: # Adds support for emojis in Markdown
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.highlight # Adds syntax highlighting to code blocks
  - pymdownx.inlinehilite # Enables inline code highlighting for non-block code
  - pymdownx.keys # Enables rendering of keyboard keys in Markdown
  - pymdownx.magiclink # Automatically converts URLs and email addresses to links
  - pymdownx.snippets # Allows including reusable content snippets in Markdown files
  - pymdownx.superfences: # Enhances fenced code blocks with custom features
      custom_fences:
        - name: mermaid # Adds support for Mermaid diagrams in Markdown
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: # Enables tabbed content sections in Markdown
      alternate_style: true # Sets an alternate style for tabs
  - pymdownx.tasklist: # Adds support for task lists in Markdown
      custom_checkbox: true # Enables custom checkboxes for task lists
  - tables # Adds support for tables in Markdown
  - toc: # Generates a table of contents based on headings
      permalink: "🔗&#xFE0E;" # Adds a permalink to each heading for easy linking

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/joel-beck/readnext

nav: # Navigation menu structure
  - Introduction: index.md
  - Setup: setup.md
  - Quick Guide: quick-guide.md
  - Background: background.md
  - User Guide: user-guide.md
