site_name: readnext
site_description: A Hybrid Recommender System for Computer Science Papers
site_url: https://joel-beck.github.io/readnext/

repo_name: readnext
repo_url: https://github.com/joel-beck/readnext

theme:
  name: material
  icon:
    logo: material/meteor # built-in icon search at https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/?h=ic#search
    repo: fontawesome/brands/github
  features:
    - content.code.copy # Adds a copy button to code blocks
    - content.tabs.link # Allows linking to specific tabs via URLs
    - navigation.expand # Expands the navigation menu for nested sections
    - navigation.footer # Displays a footer navigation menu
    - navigation.instant # Enables instant navigation without page reloads
    - navigation.tracking # Tracks the user's progress through the documentation
    - search.highlight # Highlights search terms in the search results
    - search.share # Enables sharing of search results via URL
    - search.suggest # Provides search suggestions while typing in the search bar
    - toc.follow # Automatically updates the table of contents as the user scrolls
    - toc.integrate # Integrates the table of contents into the navigation
  palette:
    - media: "(prefers-color-scheme: light)" # Light Mode
      scheme: default
      primary: "#193549"
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)" # Dark Mode
      scheme: slate
      primary: "#193549"
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"

plugins:
  - search # Enables search functionality

markdown_extensions:
  - admonition # Enables collapsible blocks with styled titles for notes, warnings, etc. in the documentation
  - footnotes # Adds support for footnotes in the Markdown files
  - pymdownx.arithmatex:
      generic: true # Enables generic output for math expressions using MathJax
  - pymdownx.betterem # Improves the handling of italic and bold text in Markdown
  - pymdownx.caret # Adds support for inserting the caret character (^) in Markdown text
  - pymdownx.details # Enables collapsible content sections using the details HTML tag in Markdown
  - pymdownx.emoji: # Adds support for emojis in Markdown files
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight: # Adds syntax highlighting to code blocks in Markdown
      use_pygments: true
      line_spans: __span
  - pymdownx.inlinehilite # Enables inline code highlighting for non-block code in Markdown
  - pymdownx.keys # Enables rendering of keyboard keys in Markdown text
  - pymdownx.magiclink # Automatically converts URLs and email addresses to links in Markdown
  - pymdownx.mark # Adds support for marking text with a highlight effect in Markdown
  - pymdownx.smartsymbols # Converts certain text symbols to their corresponding HTML entities
  - pymdownx.snippets # Allows including reusable content snippets in Markdown files
  - pymdownx.superfences # Enhances Markdown's fenced code block support
  - pymdownx.tabbed: # Enables tabbed content sections in Markdown
      alternate_style: true
  - pymdownx.tasklist: # Adds support for task lists in Markdown
      custom_checkbox: true
  - pymdownx.tilde # Adds support for strikethrough text using tilde (~~) syntax in Markdown
  - tables # Adds support for tables in Markdown files
  - toc:
      permalink: "🔗&#xFE0E;" # Adds a permalink to each heading for easy linking in the documentation

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/joel-beck/readnext

extra_javascript:
  - javascripts/mathjax.js # Enables MathJax support for LaTeX math equations
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav: # Navigation menu structure
  - Introduction: index.md
  - Installation: installation.md
  - Overview: overview.md
  - Setup: setup.md
  - Background: background.md
  - Inference: inference.md
  - Reproducibility: reproducibility.md
  - Customization: customization.md
