name: mkdocs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  pull-requests: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]
        python-version: ["3.10"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install production dependencies
        run: pdm install

      - name: Build and deploy docs to GitHub Pages
        run: pdm deploy
